
- name: install LAMP Stack
  hosts: all
  remote_user: azureuser
  become: true
  become_user: root
  gather_facts: true

- name: Include Apache
  import_playbook: apache.yaml

- name: Include MySQL
  import_playbook: mysql.yaml
